---
redisson:
  clusterServersConfig:
    nodeAddresses:
    - "redis://redis1-1:6379"
    - "redis://redis1-2:6379"
    - "redis://redis1-3:6379"
    - "redis://redis2-1:6379"
    - "redis://redis2-2:6379"
    - "redis://redis2-3:6379"
    - "redis://redis3-1:6379"
    - "redis://redis3-2:6379"
    - "redis://redis3-3:6379"
    clientName: "v1x1-{{module_name}}"
    readMode: MASTER
    masterConnectionPoolSize: 1024
    retryAttempts: 10
    failedAttempts: 10
cassandra:
  cluster_name: "Tableflippers Cluster"
  keyspace: "v1x1"
  contact_points:
  - k8s-w01.tblflp.zone
  - k8s-w02.tblflp.zone
  - k8s-w03.tblflp.zone
  - k8s-w04.tblflp.zone
  authenticated: true
  username: v1x1
  password: klx1tOCEL8otSFWNP56DNKXZ283HKB2f5borTYTcXLzO
zookeeper_connection_string: zk1:2181,zk2:2181,zk3:2181
server:
  applicationConnectors:
    - type: https
      port: 8443
      keyStorePath: /tmp/keystore.jks
      keyStorePassword: notsecure
      validateCerts: false
      validatePeers: false
  adminConnectors:
    - type: http
      port: 8081
      bindHost: 127.0.0.1