---
redisson:
  clusterServersConfig:
    nodeAddresses:
    - "//redis1-1:6379"
    - "//redis1-2:6379"
    - "//redis1-3:6379"
    - "//redis2-1:6379"
    - "//redis2-2:6379"
    - "//redis2-3:6379"
    - "//redis3-1:6379"
    - "//redis3-2:6379"
    - "//redis3-3:6379"
    clientName: v1x1
    readMode: MASTER
cassandra:
  cluster_name: "Tableflippers Cluster"
  keyspace: "v1x1"
  contact_points:
  - 198.50.235.199
  - 192.99.39.57
  - 192.95.50.35
  authenticated: true
  username: v1x1
  password: klx1tOCEL8otSFWNP56DNKXZ283HKB2f5borTYTcXLzO
zookeeper_connection_string: zk1:2181,zk2:2181,zk3:2181